"""Make the debugging workspace the homepage, sharing its existing assets.

Edit docs/debug/index.html, then run python scripts/build_workspace.py.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    html = (ROOT / "docs/debug/index.html").read_text()
    for attribute, name in [("href", "style.css"), ("src", "config.js"), ("src", "app.js")]:
        html = html.replace(f'{attribute}="{name}', f'{attribute}="debug/{name}')
    html = html.replace('href="../', 'href="./')
    html = html.replace("<!doctype html>", "<!doctype html>\n<!-- Generated by scripts/build_workspace.py; edit docs/debug/index.html. -->", 1)
    (ROOT / "docs/index.html").write_text(html)
    print("Built docs/index.html from the debugging workspace")


if __name__ == "__main__":
    main()
